# Generated by Django 5.2.3 on 2025-06-19 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('studio_type', models.CharField(choices=[('CYCLORAMA', 'Cyclorama Studio'), ('KITCHEN', 'Kitchen Studio'), ('OPEN_SPACE', 'Open Space Studio'), ('PODCAST', 'Podcast Studio'), ('AUDIO', 'Audio Recording Studio'), ('OUTDOOR', 'Outdoor Studio'), ('GREEN_SCREEN', 'Green Screen Studio'), ('BLACK_BOX', 'Black Box Studio'), ('LIFESTYLE', 'Lifestyle Studio'), ('NATURAL_LIGHT', 'Natural Light Studio')], max_length=50)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attributes', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='studios.studio')),
            ],
        ),
    ]
